### ISSUE TITLE
Missing idea.h while configuring

### ISSUE THREAD

**Issue by Gh0s7** [heipei/engine-cuda#1]
Here's my command:
./configure --prefix=/opt --with-cudatoolkitpath=/usr/local/cuda --disable-libopencl

and here's the output
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether make sets $(MAKE)... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for ANSI C header files... (cached) yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for stdint.h... (cached) yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking for memory.h... (cached) yes
checking openssl/aes.h usability... yes
checking openssl/aes.h presence... yes
checking for openssl/aes.h... yes
checking openssl/blowfish.h usability... yes
checking openssl/blowfish.h presence... yes
checking for openssl/blowfish.h... yes
checking openssl/camellia.h usability... yes
checking openssl/camellia.h presence... yes
checking for openssl/camellia.h... yes
checking openssl/cast.h usability... yes
checking openssl/cast.h presence... yes
checking for openssl/cast.h... yes
checking openssl/des.h usability... yes
checking openssl/des.h presence... yes
checking for openssl/des.h... yes
checking openssl/idea.h usability... no
checking openssl/idea.h presence... no
checking for openssl/idea.h... no
configure: error: openssl/idea.h required

idea.h seems to be in his place:
ls /opt/include/openssl/
aes.h       cast.h      dsa.h     e_os2.h     md2.h          ossl_typ.h   rc2.h        ssl3.h      ui_compat.h
asn1.h      comp.h      dso.h     err.h       md4.h          pem2.h       rc4.h        ssl.h       ui.h
asn1_mac.h  conf_api.h  dtls1.h   evp.h       md5.h          pem.h        ripemd.h     stack.h     x509.h
asn1t.h     conf.h      ebcdic.h  hmac.h      objects.h      pkcs12.h     rsa.h        store.h     x509v3.h
bio.h       crypto.h    ecdh.h    idea.h      obj_mac.h      pkcs7.h      safestack.h  symhacks.h  x509_vfy.h
blowfish.h  des.h       ecdsa.h   krb5_asn.h  ocsp.h         pq_compat.h  sha.h        tls1.h
bn.h        des_old.h   ec.h      kssl.h      opensslconf.h  pqueue.h     ssl23.h      tmdiff.h
buffer.h    dh.h        engine.h  lhash.h     opensslv.h     rand.h       ssl2.h       txt_db.h

**Comment by heipei** [comment]
`--prefix` is meant for specifying the installation directory. If you want ./configure to search under /opt you'll have to use `--includedir=/opt`

If that doesn't work you can try something like this:
`LDFLAGS="-L/opt/lib/" NVCPPFLAGS="-I/opt/include/ -I/usr/local/cuda/include" CPPFLAGS="-I/opt/include/" ./configure ...`

**Comment by Gh0s7** [comment]
With the last command the error moved to 

`checking openssl/camellia.h usability... no
checking openssl/camellia.h presence... no
checking for openssl/camellia.h... no
configure: error: openssl/camellia.h required`

I don't have camellia.h in my /opt/include/openssl dir, so I moved it from /usr/include/openssl (I guess this is the standard setup without cuda patch) but still no success.

Here's the command that I'm using:

`LDFLAGS="-L/opt/lib/" NVCPPFLAGS="-I/opt/include/ -I/usr/local/cuda/include" CPPFLAGS="-I/opt/include/" ./configure --prefix=/opt --with-cudatoolkitpath=/usr/local/cuda --disable-libopencl --includedir=/usr/include/openssl`

**Comment by heipei** [comment]
Hm, no, try it like this:
`LDFLAGS="-L/opt/lib/" NVCPPFLAGS="-I/opt/include/ -I /usr/include -I/usr/local/cuda/include" CPPFLAGS="-I/opt/include/ -I/usr/include" ./configure --prefix=/opt --with-cudatoolkitpath=/usr/local/cuda --disable-libopencl --includedir=/usr/include`

Another way to make sure camellia.h is in /opt/include is to compile your OpenSSL custom with Camellia, which you'll need to do anyway ;)

**Comment by Gh0s7** [comment]
The last one worked after rebuilding openssl with the option "enable-camellia".
Now launching make throws this error 3 times:
cmll_cuda.cu(412): error: class "camellia_key_st" has no member "u"

Should I have to open another issue? (btw thanks for your support!)
If you can tell me a way to buil it with just DES ECB support it would be great :)

**Comment by heipei** [comment]
Hm, that is strange. Could you check `camellia.h` for the `camellia_key_st` struct? It's at line 81 for me. Which version of OpenSSL are you using?

As for buidling engine-cuda without a particular cipher, there are no preprocessor flags to toggle this behaviour. You would have to edit engine-cuda.cu and remove occurences of Camellia-code manually. You'll probably also have to edit the Makefile.

**Comment by Gh0s7** [comment]
It's openssl-0.9.8k.

```
struct camellia_key_st
    {
    KEY_TABLE_TYPE rd_key;
    int bitLength;
    void (*enc)(const unsigned int *subkey, unisgned int *io);
    void (*dec)(const unsigned int *subkey, unisgned int *io);
    };
typedef struct camellia_key_st CAMELLIA_KEY;
```

that's all!

**Comment by heipei** [comment]
Hm, it should look like this:

```
struct camellia_key_st
  {
  union {
    double d; /* ensures 64-bit align */
    KEY_TABLE_TYPE rd_key;
    } u;
  int grand_rounds;
  };
typedef struct camellia_key_st CAMELLIA_KEY;
```

Try using OpenSSL 1.0.x if that is possible for you.

**Comment by Gh0s7** [comment]
It worked with openssl 1.0.1e, thanks again for your support!
